name: SecDevOps
on:
  push:
    branches:
      - master
  pull_request :
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Archive des résultats de tests
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
