name: SecDevOps
on:
  push:
    branches:
      - master
  pull_request :
    branches:
      - master
      
jobs:
  Security :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
        
      - name: Installation des dépendances dev
        run:
          pip install --upgrade pip
          pip install -r requirements/dev.txt || true
          
      - name: Installation des dépendances prod
        run: pip install -r requirements/prod.txt || true
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Snyk
        run: npm install -g snyk

      - name: Run Snyk test (dependency scan)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --file=requirements/prod.txt --json > snyk-report.json || true
        
      - name: Upload security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            snyk-report.json

